export default function emailDomainList(): Array<string> {
   return [
      "kosen-ac.jp",
      // 北海道・東北
      "hakodate-ct.ac.jp",
      "tomakomai-ct.ac.jp",
      "kushiro-ct.ac.jp",
      "asahikawa-nct.ac.jp",
      "hachinohe-ct.ac.jp",
      "ichinoseki.ac.jp",
      "sendai-nct.ac.jp",
      "tsuruoka-nct.ac.jp",
      "fukushima-nct.ac.jp",
      // 関東・甲信越
      "ibaraki-ct.ac.jp",
      "oyama-ct.ac.jp",
      "gunma-ct.ac.jp",
      "kisarazu.ac.jp",
      "tokyo-ct.ac.jp",
      "nagaoka-ct.ac.jp",
      "nagano-nct.ac.jp",
      "metro-cit.ac.jp",
      "salesio-sp.ac.jp",
      // 東海・北陸・近畿
      "nc-toyama.ac.jp",
      "ishikawa-nct.ac.jp",
      "fukui-nct.ac.jp",
      "gifu-nct.ac.jp",
      "numazu-ct.ac.jp",
      "toyama-ct.ac.jp",
      "suzuka-ct.ac.jp",
      "maizuru-ct.ac.jp",
      "akashi.ac.jp",
      "nara-k.ac.jp",
      "wakayama-nct.ac.jp",
      "toba-cmt.ac.jp",
      "cf.osakafu-u.ac.jp",
      "cf.omu.ac.jp",
      "kobe-kosen.ac.jp",
      "ict-kanazawa.ac.jp",
      "ktc.ac.jp",
      // 中国・四国
      "yonago-k.ac.jp",
      "matsue-ct.ac.jp",
      "tsuyama-ct.ac.jp",
      "kure-nct.ac.jp",
      "tokuyama.ac.jp",
      "ube-k.ac.jp",
      "anan-nct.ac.jp",
      "kagawa-nct.ac.jp",
      "niihama-nct.ac.jp",
      "kouchi-ct.ac.jp"
      "hiroshima-cmt.ac.jp",
      "oshima.ac.jp",
      "yuge.ac.jp",
      // 九州
      "kurume-nct.ac.jp",
      "ariake-nct.ac.jp",
      "kct.ac.jp",
      "sasebo.ac.jp",
      "kumamoto-nct.ac.jp",
      "oita-ct.ac.jp",
      "miyakonojo-nct.ac.jp",
      "kagoshima-ct.ac.jp",
      "okinawa-ct.ac.jp"
   ];
}
